# Generated manually for the normalized finance domain.
import decimal
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import apps.organizations.validators


class Migration(migrations.Migration):
    initial = True
    dependencies = [("organizations", "0002_organization_legal_billing_lifecycle"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="FinancialAccount", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("code", models.CharField(max_length=40)), ("name", models.CharField(max_length=160)), ("category", models.CharField(choices=[("revenue", "Revenue"), ("operating_cost", "Operating cost"), ("payroll_cost", "Payroll cost"), ("tax", "Tax"), ("investment_fund", "Investment fund"), ("insurance_premium", "Insurance premium"), ("insurance_claim", "Insurance claim"), ("commission_liability", "Commission liability")], db_index=True, max_length=32)), ("currency", models.CharField(default="USD", max_length=3, validators=[apps.organizations.validators.validate_currency])), ("is_active", models.BooleanField(default=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"))], options={"indexes": [models.Index(fields=["organization", "category"], name="fin_account_org_cat_idx")], "constraints": [models.UniqueConstraint(fields=("organization", "code"), name="unique_finance_account_code")]}),
        migrations.CreateModel(name="InvestmentFund", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("code", models.CharField(max_length=40)), ("name", models.CharField(max_length=160)), ("target_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"))], options={"constraints": [models.UniqueConstraint(fields=("organization", "code"), name="unique_investment_fund_code")]}),
        migrations.CreateModel(name="Product", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("code", models.CharField(max_length=40)), ("name", models.CharField(max_length=160)), ("is_active", models.BooleanField(default=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"))], options={"constraints": [models.UniqueConstraint(fields=("organization", "code"), name="unique_finance_product_code")]}),
        migrations.CreateModel(name="DataQualityWarning", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("code", models.CharField(max_length=60)), ("message", models.TextField()), ("source_type", models.CharField(blank=True, max_length=80)), ("source_reference", models.CharField(blank=True, max_length=160)), ("detected_at", models.DateTimeField(auto_now_add=True)), ("resolved_at", models.DateTimeField(blank=True, null=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"))]),
        migrations.CreateModel(name="ForecastRun", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("metric_type", models.CharField(choices=[("gross_profit", "Gross profit"), ("operating_profit", "Operating profit"), ("after_tax_result", "After-tax result"), ("payroll_revenue_ratio", "Payroll-to-revenue ratio"), ("product_margin", "Product margin"), ("insurance_exposure", "Insurance exposure"), ("coverage_margin", "Coverage margin"), ("commission_liability", "Commission liability")], max_length=40)), ("model_version", models.CharField(max_length=80)), ("assumptions", models.JSONField(default=dict)), ("source_data_start", models.DateField()), ("source_data_end", models.DateField()), ("created_at", models.DateTimeField(auto_now_add=True)), ("disclaimer", models.TextField(default="Prediction only — confidence ranges express uncertainty and outcomes are not guaranteed.")), ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"))]),
        migrations.CreateModel(name="InsurancePolicy", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("policy_number", models.CharField(max_length=80)), ("coverage_limit", models.DecimalField(decimal_places=2, max_digits=18)), ("commission_rate", models.DecimalField(decimal_places=4, default=decimal.Decimal("0"), max_digits=7)), ("effective_from", models.DateField()), ("effective_to", models.DateField(blank=True, null=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.organization")), ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="insurance_policies", to="finance.product"))], options={"constraints": [models.UniqueConstraint(fields=("organization", "policy_number"), name="unique_policy_number")]}),
        migrations.CreateModel(name="InsuranceClaim", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("claim_number", models.CharField(max_length=80)), ("occurred_on", models.DateField()), ("reported_on", models.DateField()), ("claimed_amount", models.DecimalField(decimal_places=2, max_digits=18)), ("reserved_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)), ("paid_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)), ("status", models.CharField(choices=[("reported", "Reported"), ("reserved", "Reserved"), ("paid", "Paid"), ("denied", "Denied"), ("closed", "Closed")], default="reported", max_length=20)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.organization")), ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="claims", to="finance.insurancepolicy"))], options={"constraints": [models.UniqueConstraint(fields=("organization", "claim_number"), name="unique_claim_number")]}),
        migrations.CreateModel(name="LedgerEntry", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("entry_date", models.DateField(db_index=True)), ("amount", models.DecimalField(decimal_places=2, max_digits=18)), ("description", models.CharField(max_length=255)), ("source_type", models.CharField(help_text="Name of the source system or record type.", max_length=80)), ("source_reference", models.CharField(help_text="Stable reference to the underlying source record.", max_length=160)), ("created_at", models.DateTimeField(auto_now_add=True)), ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="finance.financialaccount")), ("investment_fund", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="finance.investmentfund")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.organization")), ("policy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="finance.insurancepolicy")), ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="finance.product"))], options={"indexes": [models.Index(fields=["organization", "entry_date"], name="ledger_org_date_idx")], "constraints": [models.UniqueConstraint(fields=("organization", "source_type", "source_reference", "account"), name="unique_ledger_source_account")]}),
        migrations.CreateModel(name="FinancialMetric", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("metric_type", models.CharField(choices=[("gross_profit", "Gross profit"), ("operating_profit", "Operating profit"), ("after_tax_result", "After-tax result"), ("payroll_revenue_ratio", "Payroll-to-revenue ratio"), ("product_margin", "Product margin"), ("insurance_exposure", "Insurance exposure"), ("coverage_margin", "Coverage margin"), ("commission_liability", "Commission liability")], max_length=40)), ("period_start", models.DateField()), ("period_end", models.DateField()), ("value", models.DecimalField(decimal_places=4, max_digits=20)), ("source_entry_ids", models.JSONField(default=list)), ("calculated_at", models.DateTimeField(auto_now_add=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.organization")), ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="metrics", to="finance.product"))], options={"indexes": [models.Index(fields=["organization", "metric_type", "period_end"], name="metric_org_type_end_idx")]}),
        migrations.CreateModel(name="ForecastPoint", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("forecast_date", models.DateField()), ("predicted_value", models.DecimalField(decimal_places=4, max_digits=20)), ("confidence_low", models.DecimalField(decimal_places=4, max_digits=20)), ("confidence_high", models.DecimalField(decimal_places=4, max_digits=20)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.organization")), ("run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="points", to="finance.forecastrun"))], options={"constraints": [models.UniqueConstraint(fields=("run", "forecast_date"), name="unique_forecast_run_date")]}),
    ]
