# Generated by Django 5.2.4 on 2026-06-09 08:51

import apps.organizations.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_legal_billing_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('display_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('tax_identifier_reference', models.CharField(blank=True, help_text='Token or encrypted reference; never store plaintext tax IDs.', max_length=255)),
                ('jurisdiction', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ClientBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_contact', models.CharField(blank=True, max_length=200)),
                ('billing_address', models.TextField()),
                ('currency', models.CharField(max_length=3, validators=[apps.organizations.validators.validate_currency])),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30)),
                ('purchase_order_required', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_profile', to='clients.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('agreement_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('billing_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3, validators=[apps.organizations.validators.validate_currency])),
                ('termination_notice_days', models.PositiveSmallIntegerField(default=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_agreements', to='clients.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization', 'status'], name='client_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_client_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number', ''), _negated=True), fields=('organization', 'registration_number'), name='unique_client_registration_per_org'),
        ),
        migrations.AddIndex(
            model_name='clientbillingprofile',
            index=models.Index(fields=['organization', 'billing_email'], name='client_bill_email_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceagreement',
            index=models.Index(fields=['client', 'status', 'effective_from'], name='agreement_client_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceagreement',
            constraint=models.UniqueConstraint(fields=('organization', 'agreement_number'), name='unique_agreement_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='serviceagreement',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0)), name='service_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='serviceagreement',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='service_agreement_dates_valid'),
        ),
    ]
