# Generated by Django 5.2.4 on 2026-06-09 08:50

import apps.organizations.validators
import apps.security.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_legal_billing_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('name', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('employee_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('work_phone', models.CharField(blank=True, max_length=50)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('leave', 'On leave'), ('terminated', 'Terminated'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'permissions': [('view_employee_sensitive', 'Can view employee sensitive-data records')],
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3, validators=[apps.organizations.validators.validate_currency])),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('export', 'Export'), ('correction', 'Correction'), ('deletion', 'Deletion'), ('retention_review', 'Retention review')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('legal_basis', models.TextField(blank=True)),
                ('response_sha256', models.CharField(blank=True, max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_requests', to='employees.employee')),
            ],
            options={
                'permissions': [('manage_privacy_requests', 'Can review and execute employee privacy requests')],
            },
        ),
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(default='standard', max_length=50, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(max_length=3, validators=[apps.organizations.validators.validate_currency])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_plans', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='BenefitEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(max_length=3, validators=[apps.organizations.validators.validate_currency])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='employees.benefitplan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefit_enrollments', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('account_holder_encrypted', apps.security.fields.EncryptedTextField()),
                ('account_number_token', models.CharField(max_length=255)),
                ('account_fingerprint', models.CharField(help_text='Keyed hash used only for duplicate detection.', max_length=128)),
                ('routing_details_encrypted', apps.security.fields.EncryptedTextField()),
                ('currency', models.CharField(max_length=3, validators=[apps.organizations.validators.validate_currency])),
                ('is_primary', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'permissions': [('view_banking_information', 'Can view restricted employee banking information'), ('change_banking_information', 'Can change restricted employee banking information')],
            },
        ),
        migrations.CreateModel(
            name='EmployeePersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('legal_name_encrypted', apps.security.fields.EncryptedTextField(blank=True)),
                ('date_of_birth_encrypted', apps.security.fields.EncryptedTextField(blank=True)),
                ('personal_email_encrypted', apps.security.fields.EncryptedTextField(blank=True)),
                ('personal_phone_encrypted', apps.security.fields.EncryptedTextField(blank=True)),
                ('residential_address_encrypted', apps.security.fields.EncryptedTextField(blank=True)),
                ('government_id_token', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_encrypted', apps.security.fields.EncryptedTextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='personal_information', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'permissions': [('view_personal_information', 'Can view restricted employee personal information'), ('change_personal_information', 'Can change restricted employee personal information')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('jurisdiction', models.CharField(max_length=20)),
                ('tax_identifier_token', models.CharField(max_length=255)),
                ('tax_identifier_fingerprint', models.CharField(max_length=128)),
                ('elections_encrypted', apps.security.fields.EncryptedTextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_profiles', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'permissions': [('view_tax_information', 'Can view restricted employee tax information'), ('change_tax_information', 'Can change restricted employee tax information')],
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('contract_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('fixed_term', 'Fixed term'), ('casual', 'Casual'), ('contractor', 'Contractor')], max_length=30)),
                ('hours_per_week', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notice_days', models.PositiveSmallIntegerField(default=0)),
                ('terms_document_reference', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('employer', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('provider', models.CharField(max_length=200)),
                ('policy_token', models.CharField(help_text='Tokenized policy identifier; do not store plaintext policy numbers.', max_length=255)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3, validators=[apps.organizations.validators.validate_currency])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_coverages', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_assignments', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='employees.payrollproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, periods, underscores, slashes, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('title', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='employees.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('leave', 'On leave'), ('terminated', 'Terminated'), ('archived', 'Archived')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_history', to='employees.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_history', to='employees.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_history', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_history', to='employees.position')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('awarded_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('credential_reference', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3, validators=[apps.organizations.validators.validate_currency])),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('proficiency', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('years_experience', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.skill')),
            ],
        ),
        migrations.AddConstraint(
            model_name='benefitplan',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_benefit_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_department_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'status'], name='employee_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'family_name', 'given_name'], name='employee_org_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization', 'employee_number'), name='unique_employee_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('termination_date__isnull', True), ('termination_date__gte', models.F('hire_date')), _connector='OR'), name='employee_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='deduction',
            constraint=models.UniqueConstraint(fields=('employee', 'kind', 'effective_from'), name='unique_deduction_period_start'),
        ),
        migrations.AddConstraint(
            model_name='deduction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='deduction_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='deduction',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='deduction_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='commissionplan',
            constraint=models.UniqueConstraint(fields=('employee', 'kind', 'effective_from'), name='unique_commission_period_start'),
        ),
        migrations.AddConstraint(
            model_name='commissionplan',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', Decimal('1'))), name='commission_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='commissionplan',
            constraint=models.CheckConstraint(condition=models.Q(('threshold_amount__gte', 0)), name='commission_threshold_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='commissionplan',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='commission_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='benefitenrollment',
            constraint=models.UniqueConstraint(fields=('employee', 'product', 'effective_from'), name='unique_benefit_period_start'),
        ),
        migrations.AddConstraint(
            model_name='benefitenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('employee_amount__gte', 0), ('employer_amount__gte', 0)), name='benefit_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='benefitenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='benefit_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeebankaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'account_fingerprint'), name='unique_bank_fingerprint_per_org'),
        ),
        migrations.AddConstraint(
            model_name='employeebankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('is_primary', True)), fields=('employee',), name='one_primary_bank_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeetaxprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'tax_identifier_fingerprint'), name='unique_tax_fingerprint_per_org'),
        ),
        migrations.AddConstraint(
            model_name='employeetaxprofile',
            constraint=models.UniqueConstraint(fields=('employee', 'jurisdiction', 'effective_from'), name='unique_tax_period_start'),
        ),
        migrations.AddConstraint(
            model_name='employeetaxprofile',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='tax_profile_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.UniqueConstraint(fields=('organization', 'contract_number'), name='unique_contract_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('hours_per_week__gt', 0)), name='contract_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='contract_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='experience_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='insurancecoverage',
            constraint=models.UniqueConstraint(fields=('employee', 'kind', 'effective_from'), name='unique_insurance_period_start'),
        ),
        migrations.AddConstraint(
            model_name='insurancecoverage',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_amount__gte', 0)), name='insurance_coverage_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='insurancecoverage',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='insurance_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollproduct',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_payroll_product_code'),
        ),
        migrations.AddIndex(
            model_name='employeeproductassignment',
            index=models.Index(fields=['employee', 'product', 'effective_from'], name='product_assignment_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeproductassignment',
            constraint=models.UniqueConstraint(fields=('employee', 'product', 'effective_from'), name='unique_product_period_start'),
        ),
        migrations.AddConstraint(
            model_name='employeeproductassignment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='product_assignment_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_position_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='employmenthistory',
            index=models.Index(fields=['employee', 'effective_from', 'effective_to'], name='employment_history_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='employmenthistory',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='unique_employment_history_start'),
        ),
        migrations.AddConstraint(
            model_name='employmenthistory',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='employment_history_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.UniqueConstraint(fields=('employee', 'name', 'issuing_body'), name='unique_employee_qualification'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('expires_on__isnull', True), ('awarded_on__isnull', True), ('expires_on__gte', models.F('awarded_on')), _connector='OR'), name='qualification_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['employee', 'effective_from', 'effective_to'], name='salary_employee_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='unique_salary_period_start'),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='salary_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='salary_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_skill_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='employeeskill',
            constraint=models.UniqueConstraint(fields=('employee', 'skill'), name='unique_employee_skill'),
        ),
        migrations.AddConstraint(
            model_name='employeeskill',
            constraint=models.CheckConstraint(condition=models.Q(('years_experience__gte', 0)), name='skill_experience_nonnegative'),
        ),
    ]
